# Generated by Django 4.2.4 on 2023-08-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0002_rename_category_name_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
