# Generated by Django 4.2.4 on 2023-08-06 18:36

import django.db.models.deletion
import Product.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0004_alter_product_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.CreateModel(
            name="image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=Product.models.image_upload)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="Product.product",
                    ),
                ),
            ],
        ),
    ]
