# Generated by Django 4.2.4 on 2023-08-06 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Product", "0006_alter_image_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_images",
                to="Product.product",
            ),
        ),
    ]
